### ISSUE TITLE
TypeError: Error: InvalidParameterType: Expected params.ContentType to be a string

### ISSUE THREAD

**Issue by andrew-dixon** [mwishek/metalsmith-s3#6]
@mwishek - I'm getting the error:

```
TypeError: Error: InvalidParameterType: Expected params.ContentType to be a string
```

When attempting to use the plugin. I've tried setting the credentials using export and the config file but doesn't make any difference. My build file looks like this:

```
var metalsmith    = require('metalsmith');
var markdown      = require('metalsmith-markdown');
var layouts       = require('metalsmith-layouts');
var less          = require('metalsmith-less')
var htmlMinifier  = require("metalsmith-html-minifier");
var uglify        = require('metalsmith-uglify');
var s3            = require('metalsmith-s3');

metalsmith(__dirname)
  .use(markdown())
  .use(layouts({
      'engine': 'handlebars',
      'partials': 'partials'
  }))
  .use(less({
    'pattern': 'less/styles.less'
  }))
  .use(htmlMinifier())
  .use(uglify({
    'removeOriginal': true,
    'order': ['js/jquery.js','js/*.js'],
    'concat': 'js/scripts.min.js'
  }))
 .use(s3({
    action: 'write',
    bucket: 'my-s3-bucket',
    region: 'eu-west-1'
  }))
  .build(function(err) {
    if (err) throw err;
  });
```

The full error message is:

```
/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^

TypeError: Error: InvalidParameterType: Expected params.ContentType to be a string
    at result (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/lib/index.js:206:11)
    at /Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/lib/index.js:134:6
    at /Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/lib/index.js:200:5
    at done (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/async/lib/async.js:126:15)
    at Response.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/async/lib/async.js:32:16)
    at Request.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:354:18)
    at Request.callListeners (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:34:11)
    at Request.<anonymous> (/Library/WebServer/Documents/metalsmith-site/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:598:12)
```

Thanks.

**Comment by mwishek** [comment]
Hi @andrew-dixon, it seems that one of your files is not returning a valid mime-type during lookup. Can you run again with the debugger by using the following command-line:

> DEBUG=metalsmith-s3 node index.js

Replace index.js with your build file if appropriate. Assuming that worked, please post the output log.

Thanks,
Matthew

**Comment by andrew-dixon** [comment]
Hi @mwishek, I tried that and it just gives me exactly the same error output as above, or does this option write a log file somewhere else?

**Comment by mwishek** [comment]
Hi @andrew-dixon, I see the debug write came after the s3 command, so there was no debug output. I have updated the code to place the debug write before the s3 command and added the contentType to the debug output.

Please download the updated lib/index.js file and re-run with the debug command line as above. The debug output should show directly on the terminal. For example, when I run I see:

$ DEBUG=metalsmith-s3 node build
starting nonlinear.zone build...
...
  metalsmith-s3 writing file:  +475ms feed.xml with contentType =  application/xml
  metalsmith-s3 writing file:  +3ms robots.txt with contentType =  text/plain
  metalsmith-s3 writing file:  +2ms sitemap.xml with contentType =  application/xml
  metalsmith-s3 writing file:  +1ms css/bigfoot-default.css with contentType =  text/css
  metalsmith-s3 writing file:  +1ms css/main.css with contentType =  text/css
  metalsmith-s3 writing file:  +1ms categories/index.html with contentType =  text/html
  metalsmith-s3 writing file:  +1ms index.html with contentType =  text/html
...
  metalsmith-s3 write to S3 done +15s
nonlinear.zone build done!

**Comment by andrew-dixon** [comment]
@mwishek - Ok this is very odd, but using the new version of the file resolved the issue and the files loaded to S3 without issue, both running it with the debug and without. Did you make any other changes in the last week or so?

**Comment by mwishek** [comment]
@andrew-dixon, there have been no changes since your last two PRs were merged. However, there is a commit from another PR on Feb 10 that did relate to the contentType. Perhaps you had forked prior to that PR?

**Comment by andrew-dixon** [comment]
@mwishek I installed it via npm instead of forking it and the PRs I did for the docs I did directly on Github, so didn't fork it for that either. Either way it is fixed now so thanks. :-)

**Comment by PalleZingmark** [comment]
We actually also get this annoying error from time to time, it's very irregularly and without anything else being done. We clone and install our app fresh from GitHub, and build the static files 3, 4, 5 and even 20-25 times without any problem, and then all of a sudden: 

``` log
/node_modules/metalsmith-s3/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Error: InvalidParameterType: Expected params.ContentType to be a string
    at result (/node_modules/metalsmith-s3/lib/index.js:206:11)
    at /node_modules/metalsmith-s3/lib/index.js:134:6
    at /node_modules/metalsmith-s3/lib/index.js:200:5
    at done (/node_modules/metalsmith-s3/node_modules/async/lib/async.js:126:15) 
```

No files have been changed during this, and the app will not build the static files again once we see this message. 
Removing `node_modules` and install them all again will not fix this, the only thing we can do is delete the whole project and clone it again, fresh from GitHub. Then it will work again for X amounts of times before we have to do it all over again. 

Ideas?

**Comment by leviwheatcroft** [comment]
@PalleZingmark are you using the npm version or the current master?

I just ran into this the first time I used this plugin. Latest version 0.0.2 is 2 years old and doesn't include PR #2 which has something to do with contentType. I installed the current master and it worked fine (once at least)

```
npm remove --save metalsmith-s3
npm install --save mwishek/metalsmith-s3
```

**Comment by PalleZingmark** [comment]
@leviwheatcroft I believe it was the npm version. However, due to the fact that this issue, and also some other factors with Metalsmith, was such major issue for us, we decided to scrap this approach all together and custom build our own rendering engine.
